### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by EmilIvanov** [MentorMate/node-project-cli#203]
Create a config file in order to group env vars and decouple the application from the env

**Comment by sgpopov** [comment]
I think it would be nice if we parse the values to their native type - e.g. if we have the variable `SENTRY_ENABLED=false` the value would be converted to a boolean `true`. As [per zod documentation](https://github.com/colinhacks/zod#coercion-for-primitives), if we use the `.coerce` option, they would simply pass the value to a `Boolean()` and this would result to some surprising results:

```js
z.coerce.boolean().parse("tuna"); // => true
z.coerce.boolean().parse("true"); // => true
z.coerce.boolean().parse("false"); // => true
z.coerce.boolean().parse(1); // => true
z.coerce.boolean().parse([]); // => true

z.coerce.boolean().parse(0); // => false
z.coerce.boolean().parse(undefined); // => false
z.coerce.boolean().parse(null); // => false
```

My suggestion is to introduce some helper functions that could handle some of the commonly used scenarios for env variables and then validate the schema with zod:

```js
function envToBool(value: string | undefined) {
  if (!value) {
    return false;
  }

  return ['true', 'TRUE', '1'].includes(value);
}

const configSchema = z.object({
  sentry: {
    enabled: z.boolean(),
  },
});

export const config = configSchema.parse({
  sentry: {
    enabled: envToBool(process.env.SENTRY_ENABLED),
  },
});
```
